// DealFinder icon — the supplied two-slab mark.
// Source file: public/logo-mark.png (tight-cropped, black) — generated by
// scripts/process-logo.mjs from public/logo.png.

export function BrandIcon({ className }: { className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/logo-mark.png"
      alt="DealFinder"
      className={className}
    />
  );
}
